version: "3"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run ./server.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "8080:8080"
